fix changelog env

diff --git a/.github/workflows/check_version.yml b/.github/workflows/check_version.yml
--- a/.github/workflows/check_version.yml
+++ b/.github/workflows/check_version.yml
@@ -64,11 +64,11 @@ jobs:
               run: |
                   changelog=$(./get_changelog.sh ${{ env.pr_version }})
                   if [ -z "$changelog" ]; then
-                    echo "Error: No changelog found for version ${{ env.pr_version }}"
-                    exit 1
+                      echo "Error: No changelog found for version ${{ env.pr_version }}"
+                      exit 1
                   else
-                    echo "Changelog: $changelog"
-                    echo "changelog=$changelog" >> $GITHUB_ENV
+                      echo "$changelog" > changelog.txt
+                      echo "Changelog saved to changelog.txt"
                   fi
 
             # 8. Instalar dependencias y compilar el proyecto
diff --git a/.github/workflows/release_on_merge.yml b/.github/workflows/release_on_merge.yml
--- a/.github/workflows/release_on_merge.yml
+++ b/.github/workflows/release_on_merge.yml
@@ -37,9 +37,13 @@ jobs:
               id: get-changelog
               run: |
                   changelog=$(./get_changelog.sh ${{ env.version }})
-                  echo "changelog<<EOF" >> $GITHUB_ENV
-                  echo "$changelog" >> $GITHUB_ENV
-                  echo "EOF" >> $GITHUB_ENV
+                  if [ -z "$changelog" ]; then
+                      echo "Error: No changelog found for version ${{ env.version }}"
+                      exit 1
+                  else
+                      echo "$changelog" > changelog.txt
+                      echo "Changelog saved to changelog.txt"
+                  fi
 
             # 6. Crear una nueva release en GitHub
             - name: Create GitHub Release
@@ -50,7 +54,7 @@ jobs:
               with:
                   tag_name: v${{ env.version }}
                   release_name: 'Release v${{ env.version }}'
-                  body: ${{ env.changelog }}
+                  body_path: ./changelog.txt
                   draft: false
                   prerelease: false
 
